---
version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest'

additional_build_files:
    - src: ansible.cfg
      dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m ensurepip
        - ENV ANSIBLE_COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH=ignore
        - ENV ANSIBLE_LIBSSH_PUBLICKEY_ALGORITHMS=ssh-rsa
    prepend_galaxy:
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        - ARG AH_TOKEN
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_TOKEN=$AH_TOKEN
    append_final:
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        - RUN microdnf install -y crypto-policies-scripts && update-crypto-policies --set DEFAULT:SHA1 && microdnf clean all
