
---
version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:a17ebe09a69f28a183068c3597467311ba9ed77f1c3a42864404d5e343f7c2de'

additional_build_files:
    # Can be used to resolve collections from private automation hub
    - src: ansible.cfg
      dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: |
    # Ensure pip exists for whichever Python RPM becomes /usr/bin/python3 (UBI installs 3.9)
    python3-pip [platform:rhel-9 platform:centos-9]
    # Optional but recommended for network collections that compile wheels
    gcc [platform:rhel-9]
    libssh-devel [platform:rhel-9]
    python3-cryptography [platform:rhel-9]
    python3-lxml [platform:rhel-9]
    rsync [platform:rhel-9]  

options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m pip install --upgrade pip setuptools
    prepend_galaxy:
        # Add custom ansible.cfg which defines collection install sources
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        # AH_TOKEN is passed into the build command using a --build-arg
        # accept this as an ARG during this stage to reference later
        - ARG AH_TOKEN
        # Use the above ARG to define an environment variable holding
        # the token for resolving private collections
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_TOKEN=$AH_TOKEN
