---
collections:
  - name: amazon.aws
  - name: amazon.cloud
  - name: community.aws
  - name: ansible.controller
  - name: ansible.platform
  - name: ansible.posix
  - name: awx.awx
  - name: cloud.terraform
    version: 3.0.0
  - name: google.cloud
