---
collections:
  - name: amazon.aws
  - name: amazon.cloud
  - name: community.aws
  - name: ansible.controller
  - name: ansible.platform
  - name: ansible.posix
  - name: awx.awx
  - name: cloud.terraform
  - name: hashicorp.terraform
  - name: hashicorp.vault
  - name: google.cloud
  - name: azure.azcollection
